extends Node

# Some utilities for preparsing the jWord text format MMS uses

var persistent_formatting # Some data storage that needs to persist between functions
var text_data

var text_scene = preload("res://scenes/pageobjects/j_word_text.tscn")

func parse_text(data, canvas_width, canvas_height, path):
	# Instantiates a basic textbox node and gives it data
	# For precomputing shaped bounding boxes
	get_tree().root.get_viewport().set_canvas_cull_mask_bit(2, false);
	var text_instance = text_scene.instantiate()
	# This is the preload step but we give it what data we can
	text_instance.initialize_variables(null, data, path, Vector2(100, 100), null, canvas_width, canvas_height, null)
	var shape = util_Preloader.iddshapes[data["id"]] # Grab the corresponding shape
	if(shape["objecttype"] == "shape"): # Parse the data for it
		text_instance.data["shapeTextPlacements"] = util_TextShapes.parse_text_shape(shape, data, canvas_width, canvas_height, path)
	text_instance.shapedata = shape
	util_Preloader.held_text_instances[data["id"]] = text_instance

func pregenerate_text_for_shape(filepath, width): # Parse through a text box
	var parsed_content = parse_text_content(filepath)
	var attributes = parsed_content.attributes
	var lines = parsed_content.lines
	
	# Resize everything to something more useable
	var scale_factor = width / float(attributes["pagewidth"].to_int()) / 2.
	
	persistent_formatting = {} # Clear the persistent data storage
	text_data = []
	for line in lines: # Parse line by line
		pregenerate_line_for_shape(line, scale_factor)

class TextContent:
	var attributes
	var lines
	var is_table_of_contents

class LineOfText:
	var styles
	var blips

func parse_text_content(filepath): # Parse through the xml file
	var parser = XMLParser.new()
	parser.open(filepath)
	var text_block_data = {}
	var text = []
	while parser.read() != ERR_FILE_EOF: # Get all the relevant data from the xml
		if(parser.get_node_type() == XMLParser.NODE_ELEMENT):
			if(parser.get_node_name() == "tns:section"):
				text_block_data = util_ExtraXML.parse_attributes(parser)
			if(parser.get_node_name() == "tns:p"):
				text.append(parse_text_line(parser))
	var is_contents = check_for_contents(text) # Check if this is a table of contents
	var content = TextContent.new()
	content.attributes = text_block_data
	content.lines = text
	content.is_table_of_contents = is_contents
	return content


func parse_text_line(parser): # Get the data of a single line from an xml
	var line_attributes = util_ExtraXML.parse_attributes(parser) # Style from attributes
	var line_blips = [] # A bunch of text elements that make up the line
	while true:
		parser.read()
		if(parser.get_node_type() == XMLParser.NODE_ELEMENT_END && parser.get_node_name() == "tns:p"):
			break # End of line, we are done
		if(parser.get_node_type() == XMLParser.NODE_ELEMENT && parser.get_node_name() == "tns:txt"):
			# Text block has text and style attributes
			line_blips.append([util_ExtraXML.parse_attributes(parser), util_ExtraXML.get_text_contents(parser)])
	var line = LineOfText.new()
	line.blips = line_blips
	line.styles = line_attributes
	return line

func pregenerate_line_for_shape(line, scale_factor):
	# Get the line data
	var _line_styles = line.styles # Line styles dont really matter for shapes
	var line_blips = line.blips
	
	for blip in line_blips: # Lines are divided into chunks we call blips
		get_style_from_blip(blip, scale_factor) # Style is stored in a persistent global variable
		add_text_to_line(blip[1]) # Add it to the overall data

func get_style_from_blip(blip, scale_factor):
	# Blip (n.): A small piece of text that has been broken off a larger block arbitrarily
	# without any attention paid to the grammatical relevance of that piece on its own
	
	# The jWord files generated by MMS divide lines into chunks that sometimes have different styling,
	# sometimes don't. They often seem to be cut off in strange places
	# We call these chunks 'blips'
	
	var blip_style = blip[0]
	
	# Grab the bold italics and underline
	var bold = blip_style.has("fstyle") && blip_style["fstyle"].contains("b")
	var italics = blip_style.has("fstyle") && blip_style["fstyle"].contains("i")
	var underline = blip_style.has("fstyle") && blip_style["fstyle"].contains("u")
	persistent_formatting["bold"] = bold
	persistent_formatting["italics"] = italics
	persistent_formatting["underline"] = underline
	
	# Get font size
	var current_font_size = round(float(blip_style["fs"].to_int()) * scale_factor)
	persistent_formatting["fontSize"] = current_font_size
	if(blip_style.has("color")):
		persistent_formatting["color"] = Color(blip_style["color"])
		
	if(!blip_style.has("font")):
		return
	
	var font_name = blip_style["font"] + (" Bold" if bold else "") + (" Italic" if italics else "")
	var font;
	if(util_DictionaryMappings.specialFontsDict.has(blip_style["font"])):
		# Check if it's a special font packaged with MMS
		font = load("res://fonts/"+util_DictionaryMappings.specialFontsDict[blip_style["font"]])
	else:
		if(!util_Preloader.system_fonts_dict.has(font_name)): 
			# If we don't have the font loaded already we have to pick it up
			var new_font = SystemFont.new()
			new_font.font_italic = italics
			new_font.font_weight = 700 if bold else 400
			var font_names = PackedStringArray()
			if(util_DictionaryMappings.system_default_fonts_dict.has(blip_style["font"])):
				# Check if it's a "system default" font like "Monospaced" or "Sans-Serif"
				# And map from Java's to Godot's names for these fonts
				font_names.append(util_DictionaryMappings.system_default_fonts_dict[blip_style["font"]])
			else:
				# Otherwise look for the styled and unstyled fonts
				font_names.append(blip_style["font"])
				font_names.append(font_name)
			var font_preloaded = false
			for fn in font_names: # Loop through fonts
				if(util_Preloader.preloaded_fonts_dict.has(fn)): # See if we've preloaded it already
					util_Preloader.system_fonts_dict[font_name] = util_Preloader.preloaded_fonts_dict[fn]
					font_preloaded = true
			if(!font_preloaded): # Otherwise we let Godot look through system fonts
				new_font.set_font_names(font_names)
				# Add it to the loaded system fonts dictionary
				util_Preloader.system_fonts_dict[font_name] = new_font
		font = util_Preloader.system_fonts_dict[font_name] # Use the font
	var font_variation = FontVariation.new() # We need to make a variation for some extra formatting stuff
	font_variation.base_font = font
	if(blip_style.has("expnd")): # More/less space between glyphs
		var expandFactor = float(blip_style["expnd"])/(current_font_size) * 9/5
		font_variation.set_spacing(TextServer.SPACING_GLYPH, expandFactor)
	persistent_formatting["font"] = font_variation # Add the font as our current format

func check_for_contents(text): 
	# Check if a textbox wants a table of contents
	var text_string = ""
	for line in text:
		for blip in line.blips:
			text_string += blip[1] # Loop through to convert to ordinary string
	if(text_string.contains("[CONTENTS]")): # Look for a contents tag
		return true
	return false

func add_text_to_line(text): 
	# Add a piece of text to the overall, with its relevant formatting
	text_data.append([persistent_formatting.duplicate(), text])
